name: earlephilhower_arduino-pico
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 2 * * *'
jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      modified: ${{steps.git-check.outputs.modified}}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN  }}
      - name: Fetch release version for arduino-cli
        run: |
          curl -sL https://api.github.com/repos/arduino/arduino-cli/releases/latest | \
          jq -r ".tag_name" > release-versions/arduino-cli-latest.txt
      - name: Fetch release version for earlephilhower_arduino-pico
        run: |
          curl -sL https://api.github.com/repos/earlephilhower/arduino-pico/releases/latest | \
          jq -r ".tag_name" > release-versions/earlephilhower_arduino-pico-latest.txt
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'Pierre Constantineau'
          git config --global user.email 'your-email@users.noreply.github.com'
          git commit -am "New release version - earlephilhower_arduino-pico"
          git push


  build-ghcr:
    needs: get-version
    if: ${{ needs.get-version.outputs.modified == 'true' }}
    uses: jpconstantineau/Docker_RP2040/.github/workflows/build-image-ghcr.yml@main